### ISSUE TITLE
Prometheus monitoring

### ISSUE THREAD

**Issue by ahinko** [ahinko/k8s-cluster#11]
We do not currently have any type of monitoring of the cluster. We should set up Prometheus and Grafana.

## Todo
- [ ] [Set up Prometheus and Grafana](https://github.com/prometheus-community/helm-charts/tree/main/charts)
- [ ] Add dashboards to Grafana
- [ ] [Monitor Flux](https://toolkit.fluxcd.io/guides/monitoring/)
- [ ] Monitor Vault & Consul
- [ ] Monitor Rook + Ceph
- [ ] [Monitor Docker hub rate limiting](https://blog.viadee.de/en/monitoring-the-docker-hub-rate-limit-with-prometheus). This might not be interesting when we implement #145 
- [ ] [Monitor Unifi](https://community.ui.com/questions/UniFi-Poller-Store-UniFi-Controller-Metrics-in-Prometheus-or-InfluxDB/58a0ea34-d2b3-41cd-93bb-d95d3896d1a1)
- [ ] What else can we monitor? Cert Manager? Actions runners?

## Links
- https://sysdig.com/blog/kubernetes-monitoring-prometheus/
- https://github.com/kubernetes/node-problem-detector
