### ISSUE TITLE
High Availability Cluster

### ISSUE THREAD

**Issue by ahinko** [ahinko/k8s-cluster#4]
Redo the cluster and setup with high availability. Use keepalived to have a working VIP and HAProxy that load balances between the server nodes.

## Todo
- [x] Add Ansible linting
- [x] Create Ansible role for Keepalived
- [x] Create Ansible role for HAProxy
- [x] Create Ansible role that sets up auth credentials and url for the private docker registry. Create the file `/etc/rancher/k3s/registries.yaml` and populate with the needed information.
- [x] ~~We either need documentation for each command using k3sup OR~~ create an Ansible role for installing k3s on the server and agent nodes and join the cluster.
- [x] Update the bootstrap script to use Calico instead of Flannel
- [ ] Fix any issues with the bootstrap script
- [ ] Update any documentation that needs updating

## Links
- https://kvaps.medium.com/for-make-this-scheme-more-safe-you-can-add-haproxy-layer-between-keepalived-and-kube-apiservers-62c344283076
- https://kvaps.medium.com/creating-high-available-baremetal-kubernetes-cluster-with-kubeadm-and-keepalived-simplest-guide-71766d5e25ae
- https://thenewstack.io/tutorial-configure-cloud-native-edge-infrastructure-with-k3s-calico-portworx/
