### ISSUE TITLE
Nextcloud

### ISSUE THREAD

**Issue by ahinko** [ahinko/k8s-cluster#8]
Set up Nextcloud in the cluster and replace the current instance. We should go for the easiest possible installation using a Helm chart that includes a database and use NFS share instead of a more advanced setup with Postgres and Minio as a block-storage. We do not want to have to deal with the complexity that it would add.

## Todo:
- [ ] [HelmRelease](https://github.com/nextcloud/helm/tree/master/charts/nextcloud)
- [ ] PVC (NFS) + Rook (config etc)
- [ ] Backup Rook PV

## Links
- https://vitobotta.com/2021/02/15/nextcloud-kubernetes-s3-primary-storage/
